package com.mycompany.proyectob;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author emely
 */
public class Inventario extends javax.swing.JFrame {

    private libros libros;

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();

        pintarTabla();
    }

    private void pintarTabla() {
        DefaultTableModel t = new DefaultTableModel(new String[]{"titulo", "autor", "precio", "cantidad", "genero"}, ProyectoB.libros.size());
        jTable_inventario.setModel(t);

        TableModel tabla = jTable_inventario.getModel();

        for (int i = 0; i < ProyectoB.libros.size(); i++) {
            libros l = ProyectoB.libros.get(i);
            tabla.setValueAt(l.titulo, i, 0);
            tabla.setValueAt(l.autor, i, 1);
            tabla.setValueAt(l.precio, i, 2);
            tabla.setValueAt(l.cantidad, i, 3);
            tabla.setValueAt(l.genero, i, 4);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_regresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_inventario = new javax.swing.JTable();
        jTextField_cantidad = new javax.swing.JTextField();
        jTextField_genero = new javax.swing.JTextField();
        jButton_modificar = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_borrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_titulo = new javax.swing.JTextField();
        jTextField_autor = new javax.swing.JTextField();
        jTextField_precio = new javax.swing.JTextField();
        jButton_exportar = new javax.swing.JButton();
        jButton_importar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Inventario de libros");

        jButton_regresar.setBackground(new java.awt.Color(255, 204, 204));
        jButton_regresar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_regresar.setText("Cerrar");
        jButton_regresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173)
                .addComponent(jButton_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_regresar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jTable_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_inventario);

        jButton_modificar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_modificar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_modificar.setText("modificar");
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });

        jButton_guardar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_guardar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jLabel2.setText("Titulo:");

        jButton_borrar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_borrar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_borrar.setText("Borrar");
        jButton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jLabel3.setText("Autor:");

        jLabel4.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Genero:");

        jLabel5.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jLabel6.setText("Cantidad:");

        jButton_exportar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_exportar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_exportar.setText("Exportar");
        jButton_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exportarActionPerformed(evt);
            }
        });

        jButton_importar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_importar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_importar.setText("Importar");
        jButton_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_importarActionPerformed(evt);
            }
        });

        jButton_limpiar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_limpiar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_limpiar.setText("Limpiar archivo");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_titulo)
                            .addComponent(jTextField_autor)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_exportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_importar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_modificar)
                    .addComponent(jButton_exportar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar)
                    .addComponent(jButton_importar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_borrar)
                    .addComponent(jButton_limpiar))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_regresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_regresarActionPerformed

    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
        int modificar = jTable_inventario.getSelectedRow();
        if (modificar > -1) {
            libros = ProyectoB.libros.get(modificar);
            jTextField_titulo.setText(libros.titulo);
            jTextField_autor.setText(libros.autor);
            jTextField_precio.setText(String.valueOf(libros.precio)); // Para mostrar un double como String (String.valueOf)
            jTextField_cantidad.setText(String.valueOf(libros.cantidad)); // Para mostrar un int como String
            jTextField_genero.setText(libros.genero);
        } else {
            JOptionPane.showMessageDialog(this, "selccione un elemento a modificar");
        }
    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed

        if (libros != null) {
            String titulo = jTextField_titulo.getText();
            String autor = jTextField_autor.getText();
            String precioTexto = jTextField_precio.getText();
            String cantidadTexto = jTextField_cantidad.getText();
            String genero = jTextField_genero.getText();

            // Actualiza los atributos directamente
            libros.titulo = titulo;
            libros.autor = autor;
            // Conversión de texto a double para precio
            double precio = Double.parseDouble(precioTexto);
            libros.precio = precio; // Asignar a libros.precio

            // Conversión de texto a int para cantidad
            int cantidad = Integer.parseInt(cantidadTexto);
            libros.cantidad = cantidad; // Asignar a libros.cantidad
            libros.genero = genero;

            pintarTabla();
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Fila"+jTable1.getSelectedRow()); -- metodo para mostrar que fila fue seleccionada--

        int borrar = jTable_inventario.getSelectedRow();
        if (borrar > -1) {
            if (borrar == 0) {
                JOptionPane.showMessageDialog(this, "No puede eliminar el libro");
            } else {

                if (JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar el libro") == 0) {
                    ProyectoB.libros.remove(borrar);
                    pintarTabla();
                    JOptionPane.showMessageDialog(this, "libro eliminado");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un elemento a borrar");
        }
    }//GEN-LAST:event_jButton_borrarActionPerformed

    private void jButton_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exportarActionPerformed
        JSONArray librosArray = new JSONArray();

        for (libros libro : ProyectoB.libros) {
            JSONObject libroObject = new JSONObject();
            libroObject.put("titulo", libro.titulo);
            libroObject.put("autor", libro.autor);
            libroObject.put("precio", libro.precio);
            libroObject.put("cantidad", libro.cantidad);
            libroObject.put("genero", libro.genero);

            librosArray.add(libroObject);
        }

        try (FileWriter file = new FileWriter("inventariolibros.json")) {
            file.write(librosArray.toJSONString());
            file.flush();
            JOptionPane.showMessageDialog(this, "Inventario exportado a inventariolibros.json");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_exportarActionPerformed

    private void jButton_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_importarActionPerformed
        // Crear un objeto JSONParser
        JSONParser parser = new JSONParser();

        try {
            // Leer el archivo JSON
            Object obj = parser.parse(new FileReader("inventariolibros.json"));
            JSONArray librosArray = (JSONArray) obj;

            // Limpiar la lista de libros existente
            ProyectoB.libros.clear();

            // Iterar sobre el array y agregar libros a la lista
            for (Object libroObj : librosArray) {
                JSONObject libroJSON = (JSONObject) libroObj;

                // Crear un nuevo libro y establecer sus propiedades
                libros libro = new libros();
                libro.titulo = (String) libroJSON.get("titulo");
                libro.autor = (String) libroJSON.get("autor");
                libro.precio = Double.parseDouble(libroJSON.get("precio").toString());
                libro.cantidad = Integer.parseInt(libroJSON.get("cantidad").toString());
                libro.genero = (String) libroJSON.get("genero");

                // Agregar el libro a la lista
                ProyectoB.libros.add(libro);
            }

            // Pintar la tabla con los nuevos datos
            pintarTabla();
            JOptionPane.showMessageDialog(this, "Inventario importado correctamente.");
        } catch (IOException | ParseException e) {
            JOptionPane.showMessageDialog(this, "Error al importar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_importarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        try (FileWriter file = new FileWriter("inventariolibros.json", false)) {
            // Simplemente no escribimos nada para limpiar el archivo
            file.write(""); // Sobrescribir el archivo con un contenido vacío
            file.flush();
            JOptionPane.showMessageDialog(this, "Archivo limpiado correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al limpiar el archivo: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_borrar;
    private javax.swing.JButton jButton_exportar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_importar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JButton jButton_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_inventario;
    private javax.swing.JTextField jTextField_autor;
    private javax.swing.JTextField jTextField_cantidad;
    private javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_precio;
    private javax.swing.JTextField jTextField_titulo;
    // End of variables declaration//GEN-END:variables
}
