package com.mycompany.proyectob;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author emely
 */
public class librosvendidos extends javax.swing.JFrame {

    /**
     * Creates new form librosvendidos
     */
    public librosvendidos() {
        initComponents();
        pintarTabla();
    }

    private void pintarTabla() {
        DefaultTableModel t = new DefaultTableModel(new String[]{"Fecha", "Titulo", "Cantidad", "Precio"}, ProyectoB.libros2.size());
        jTable1.setModel(t);

        TableModel tabla = jTable1.getModel();

        for (int i = 0; i < ProyectoB.libros2.size(); i++) {
            libros2 l = ProyectoB.libros2.get(i);
            tabla.setValueAt(l.fecha, i, 0);
            tabla.setValueAt(l.titulo_venta, i, 1);
            tabla.setValueAt(l.cantidad_venta, i, 2);
            tabla.setValueAt(l.precio_venta, i, 3);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton_exportar = new javax.swing.JButton();
        jButton_limpiarcsv = new javax.swing.JButton();
        jButton_importar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Libros vendidos");

        salir.setBackground(new java.awt.Color(255, 204, 204));
        salir.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        salir.setText("Regresar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138)
                .addComponent(salir)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salir))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_exportar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_exportar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_exportar.setText("Exportar");
        jButton_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exportarActionPerformed(evt);
            }
        });

        jButton_limpiarcsv.setBackground(new java.awt.Color(255, 153, 153));
        jButton_limpiarcsv.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_limpiarcsv.setText("Limpiar CSV");
        jButton_limpiarcsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarcsvActionPerformed(evt);
            }
        });

        jButton_importar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_importar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jButton_importar.setText("Importar");
        jButton_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_importarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_exportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_importar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_limpiarcsv)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton_exportar)
                    .addComponent(jButton_importar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_limpiarcsv)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pintarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void jButton_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exportarActionPerformed
        try (PrintWriter escribir = new PrintWriter(new FileWriter("rutalibrosvendidos.csv"))) {
            // Escribir encabezados en el CSV
            escribir.println("Título,Cantidad,Precio,Fecha");

            for (libros2 c : ProyectoB.libros2) {
                // Escribir cada libro en el CSV
                escribir.printf("%s,%d,%.2f,%s%n", c.titulo_venta, c.cantidad_venta, c.precio_venta, c.fecha);
            }

            JOptionPane.showMessageDialog(this, "Libros exportados exitosamente a CSV.");
        } catch (IOException ex) {
            Logger.getLogger(librosvendidos.class.getName()).log(Level.SEVERE, "Error al exportar a CSV: " + ex.getMessage(), ex);
        }
    }//GEN-LAST:event_jButton_exportarActionPerformed

    private void jButton_limpiarcsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarcsvActionPerformed
        ProyectoB.libros2.clear();

        JOptionPane.showMessageDialog(this, "libros limpiados exitosamente.");

        // Limpiar el archivo CSV
        try (PrintWriter escribir = new PrintWriter(new FileWriter("rutalibrosvendidos.csv"))) {
            // Este bloque simplemente crea un archivo vacío.
        } catch (IOException ex) {
            Logger.getLogger(librosvendidos.class.getName()).log(Level.SEVERE, "Error al limpiar el archivo CSV: " + ex.getMessage(), ex);
        }


    }//GEN-LAST:event_jButton_limpiarcsvActionPerformed

    private void jButton_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_importarActionPerformed
       DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0); // Limpia la tabla antes de cargar nuevos datos
    ProyectoB.libros2.clear(); // Limpia la lista de libros antes de importar

    try (BufferedReader lector = new BufferedReader(new FileReader("rutalibrosvendidos.csv"))) {
        String linea;
        boolean esPrimeraLinea = true; // Para omitir la línea de encabezado
        while ((linea = lector.readLine()) != null) {
            if (esPrimeraLinea) {
                esPrimeraLinea = false; // Omitir encabezado
                continue;
            }

            String[] partes = linea.split(","); // Divide la línea en partes usando el separador ','
            if (partes.length == 4) { // Asegúrate de que hay suficientes partes
                String fecha = partes[3]; // Cambia el índice para que coincida con el formato correcto
                String titulo_venta = partes[0];
                int cantidad_venta = Integer.parseInt(partes[1]);
                double precio_venta = Double.parseDouble(partes[2]);

                // Crear un nuevo objeto libros2 y agregarlo a la lista
                libros2 libro = new libros2();
                libro.titulo_venta = titulo_venta;
                libro.cantidad_venta = cantidad_venta;
                libro.precio_venta = precio_venta;
                libro.fecha = fecha;

                ProyectoB.libros2.add(libro); // Añadir a la lista de libros
                modelo.addRow(new Object[]{fecha, titulo_venta, cantidad_venta, precio_venta}); // Añadir a la tabla
            } else {
                JOptionPane.showMessageDialog(this, "Formato de línea inválido: " + linea);
            }
        }
        JOptionPane.showMessageDialog(this, "Libros cargados exitosamente desde el archivo.");
    } catch (IOException ex) {
        Logger.getLogger(Creacion_cupones.class.getName()).log(Level.SEVERE, "Error al cargar libros: " + ex.getMessage(), ex);
        JOptionPane.showMessageDialog(this, "Error al cargar el archivo: " + ex.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error en formato numérico: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton_importarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_exportar;
    private javax.swing.JButton jButton_importar;
    private javax.swing.JButton jButton_limpiarcsv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
