package com.mycompany.proyectob;

import javax.swing.JOptionPane;

/**
 *
 * @author emely
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_ingresar = new javax.swing.JButton();
        jButton_crear_cuenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_guardarProgreso = new javax.swing.JButton();
        jButton_SubirProgreso = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("libreria");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel3.setFont(new java.awt.Font("URW Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mi ");

        jLabel4.setFont(new java.awt.Font("URW Gothic", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Libreria");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel1.setText("Usuarios");

        jTextField_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel2.setText("Password");

        jButton_ingresar.setBackground(new java.awt.Color(255, 153, 153));
        jButton_ingresar.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_ingresar.setText("Ingresar");
        jButton_ingresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresarActionPerformed(evt);
            }
        });

        jButton_crear_cuenta.setBackground(new java.awt.Color(255, 153, 153));
        jButton_crear_cuenta.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jButton_crear_cuenta.setText("Crear cuenta");
        jButton_crear_cuenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_crear_cuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_crear_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crear_cuentaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel5.setText("¡Bienvenido!");

        jLabel6.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel6.setText("-----------¿No tienes cuenta?------------");

        jButton_guardarProgreso.setBackground(new java.awt.Color(255, 153, 153));
        jButton_guardarProgreso.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_guardarProgreso.setText("Guardar progreso");
        jButton_guardarProgreso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_guardarProgreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_guardarProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarProgresoActionPerformed(evt);
            }
        });

        jButton_SubirProgreso.setBackground(new java.awt.Color(255, 153, 153));
        jButton_SubirProgreso.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_SubirProgreso.setText("Subir progreso");
        jButton_SubirProgreso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_SubirProgreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_SubirProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubirProgresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_usuario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_password)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 132, Short.MAX_VALUE)
                        .addComponent(jButton_crear_cuenta)
                        .addGap(124, 124, 124))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_SubirProgreso)
                    .addComponent(jButton_guardarProgreso))
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_guardarProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_SubirProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton_crear_cuenta)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(120, 120, 120)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_crear_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crear_cuentaActionPerformed
        nuevo_usuario v = new nuevo_usuario();
        v.setVisible(true);
    }//GEN-LAST:event_jButton_crear_cuentaActionPerformed

    private void jButton_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ingresarActionPerformed
        // Creamos el metodo para ingresar verificando la contraseña y usuario

        //se obtiene el texto ingresado en el texfield
        String Usuario = jTextField_usuario.getText();
        String password = jTextField_password.getText();

        //variable inicializada con un false usada para determinar si las credenciales coinciden con las ingresadas
        boolean existe = false;

        // creamos un blucle for each, llamamos ala clase usuario creamos la variable u llamamos a la ventana ProyectoB y la lista usuarios
        // los : es para indicar que cada elemento en. El elemento que sigue
        for (usuario u : ProyectoB.usuarios) {
            // if toda la sentencia dentro debe de ser verdadera osea true
            // u es un objeto de la clase usuario que se obtiene del bucle foreach
            //equals metodo para comparar dos cadenas (Usuario contiene lo que fue ingresado desde la interfaz) lo mismo para (password)
            // && para combinar las dos condiciones
            // el u.usuario.equals(Usuario)
            // usuario y password son atributos del objeto u
            if (u.usuario.equals(Usuario) && u.password.equals(password)) {
                // indicacion que el usuario fue encontrado
                existe = true;
                if (u.rol == 1) {
                    ventana_administrador v = new ventana_administrador();
                    v.setVisible(true);
                } else {
                    ventana_vendedor v = new ventana_vendedor(u);
                    v.setVisible(true);
                }
            }
        }
        if (existe == false) {
            JOptionPane.showMessageDialog(this, "Usuario o password incorrecto");
        }

    }//GEN-LAST:event_jButton_ingresarActionPerformed

    private void jButton_guardarProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarProgresoActionPerformed
    try {
        // Crear un objeto Datos con todas las listas
        Datos datos = new Datos(ProyectoB.usuarios, ProyectoB.libros, ProyectoB.Cupones,
                                 ProyectoB.clientes, ProyectoB.libros2, ProyectoB.ventas);
        
        // Guardar todos los datos en un solo archivo
        Persistencia.guardarDatos("todosLosDatos.bin", datos);
        
        // Mensaje de confirmación
        JOptionPane.showMessageDialog(null, "Progreso guardado correctamente en un solo archivo.");
    } catch (Exception e) {
        // Manejo de errores
        JOptionPane.showMessageDialog(null, "Error al guardar el progreso: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton_guardarProgresoActionPerformed

    private void jButton_SubirProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubirProgresoActionPerformed
 try {
        // Cargar los datos desde el archivo
        Datos datosCargados = (Datos) Persistencia.cargarDatos("todosLosDatos.bin");
        
        if (datosCargados != null) {
            // Aquí puedes procesar los datos cargados
            ProyectoB.usuarios = datosCargados.usuarios;
            ProyectoB.libros = datosCargados.libros;
            ProyectoB.Cupones = datosCargados.cupones;
            ProyectoB.clientes = datosCargados.clientes;
            ProyectoB.libros2 = datosCargados.libros2;
            ProyectoB.ventas = datosCargados.ventas;

            // Mensaje de confirmación
            JOptionPane.showMessageDialog(null, "Progreso subido correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudieron cargar los datos.");
        }
    } catch (Exception e) {
        // Manejo de errores
        JOptionPane.showMessageDialog(null, "Error al subir el progreso: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton_SubirProgresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SubirProgreso;
    private javax.swing.JButton jButton_crear_cuenta;
    private javax.swing.JButton jButton_guardarProgreso;
    private javax.swing.JButton jButton_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
