/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectob;

import javax.swing.JOptionPane;

/**
 *
 * @author emely
 */
public class Menu_vendedores extends javax.swing.JFrame {
private usuario usuarioActual;
    

    /**
     * Creates new form Menu_vendedores
     */
    public Menu_vendedores(usuario usuario) {
        initComponents();
        this.usuarioActual = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mi_perfil = new javax.swing.JMenu();
        Realizar_ventas = new javax.swing.JMenu();
        jMenu_lvendidos = new javax.swing.JMenu();
        Consultar_ventas = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(454, 50));

        mi_perfil.setText("Mi perfil");
        mi_perfil.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        mi_perfil.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mi_perfilMenuSelected(evt);
            }
        });
        jMenuBar1.add(mi_perfil);

        Realizar_ventas.setBorder(null);
        Realizar_ventas.setText("  Realizar ventas  ");
        Realizar_ventas.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        Realizar_ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Realizar_ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Realizar_ventas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Realizar_ventasMenuSelected(evt);
            }
        });
        jMenuBar1.add(Realizar_ventas);

        jMenu_lvendidos.setText("Libros vendidos");
        jMenu_lvendidos.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jMenu_lvendidos.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_lvendidosMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_lvendidos);

        Consultar_ventas.setText("Consultar ventas");
        Consultar_ventas.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        Consultar_ventas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Consultar_ventasMenuSelected(evt);
            }
        });
        jMenuBar1.add(Consultar_ventas);

        salir.setText("Salir");
        salir.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        salir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                salirMenuSelected(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Realizar_ventasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Realizar_ventasMenuSelected
        Ventas c = new Ventas();
        c.setVisible(true);
    }//GEN-LAST:event_Realizar_ventasMenuSelected

    private void jMenu_lvendidosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_lvendidosMenuSelected
        librosvendidos v = new librosvendidos();
        v.setVisible(true);
    }//GEN-LAST:event_jMenu_lvendidosMenuSelected

    private void Consultar_ventasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Consultar_ventasMenuSelected
        Consultar_ventas v = new Consultar_ventas();
        v.setVisible(true);
    }//GEN-LAST:event_Consultar_ventasMenuSelected

    private void mi_perfilMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mi_perfilMenuSelected
     Perfilvendedor perfil = new Perfilvendedor(usuarioActual); // Asegúrate de que usuarioActual esté definido
    perfil.setVisible(true); // Esto debería abrir la ventana
    }//GEN-LAST:event_mi_perfilMenuSelected

    private void salirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_salirMenuSelected
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirMenuSelected

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultar_ventas;
    private javax.swing.JMenu Realizar_ventas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenu_lvendidos;
    private javax.swing.JMenu mi_perfil;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
