package com.mycompany.proyectob;

/**
 *
 * @author emely
 */
public class ventana_administrador extends javax.swing.JFrame {

    /**
     * Creates new form ventana_administrador
     */
    public ventana_administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_consultausuario = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        nuevos_libros = new javax.swing.JMenuItem();
        inventario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_creacioncupones = new javax.swing.JMenuItem();
        jMenuItem_inventacupones = new javax.swing.JMenuItem();
        jMenu_cv = new javax.swing.JMenu();
        jMenu_salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de administrador");

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(429, 50));

        jMenu_consultausuario.setBorder(null);
        jMenu_consultausuario.setText(" Consulta de usuarios  ");
        jMenu_consultausuario.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        jMenu_consultausuario.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_consultausuarioMenuSelected(evt);
            }
        });
        jMenu_consultausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_consultausuarioActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_consultausuario);

        jMenu2.setBorder(null);
        jMenu2.setText("  Libros  ");
        jMenu2.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });

        nuevos_libros.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        nuevos_libros.setText("Nuevos libros");
        nuevos_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevos_librosActionPerformed(evt);
            }
        });
        jMenu2.add(nuevos_libros);

        inventario.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        inventario.setText("Inventario");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        jMenu2.add(inventario);

        jMenuBar1.add(jMenu2);

        jMenu1.setBorder(null);
        jMenu1.setText(" Cupones ");
        jMenu1.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        jMenuItem_creacioncupones.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jMenuItem_creacioncupones.setText("Creacion de cupones");
        jMenuItem_creacioncupones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_creacioncuponesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_creacioncupones);

        jMenuItem_inventacupones.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jMenuItem_inventacupones.setText("Inventario de cupones");
        jMenuItem_inventacupones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inventacuponesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_inventacupones);

        jMenuBar1.add(jMenu1);

        jMenu_cv.setText(" Consultar Ventas ");
        jMenu_cv.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jMenu_cv.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_cvMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_cv);

        jMenu_salir.setText("  Salir  ");
        jMenu_salir.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        jMenu_salir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_salirMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_consultausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_consultausuarioActionPerformed
        //es el de menuselected no este porque si no se abre, este va cuando se agregan items
    }//GEN-LAST:event_jMenu_consultausuarioActionPerformed

    private void jMenu_consultausuarioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_consultausuarioMenuSelected
        // Realizaremos la consulta de los usuarios creados
        Consulta_usuarios c = new Consulta_usuarios();
        c.setVisible(true);
    }//GEN-LAST:event_jMenu_consultausuarioMenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuSelected

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        // apertura del inventario de libros

        Inventario i = new Inventario();
        i.setVisible(true);
    }//GEN-LAST:event_inventarioActionPerformed

    private void nuevos_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevos_librosActionPerformed
        // apertura de nuevos libros
        Nuevos_libros n = new Nuevos_libros();
        n.setVisible(true);
    }//GEN-LAST:event_nuevos_librosActionPerformed

    private void jMenu_salirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_salirMenuSelected
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jMenu_salirMenuSelected

    private void jMenuItem_creacioncuponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_creacioncuponesActionPerformed
        Creacion_cupones c = new Creacion_cupones();
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem_creacioncuponesActionPerformed

    private void jMenuItem_inventacuponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inventacuponesActionPerformed
        inventario_cupones i = new inventario_cupones();
        i.setVisible(true);
    }//GEN-LAST:event_jMenuItem_inventacuponesActionPerformed

    private void jMenu_cvMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_cvMenuSelected
        // TODO add your handling code here:
        Consultar_ventas v = new Consultar_ventas();
        v.setVisible(true);
    }//GEN-LAST:event_jMenu_cvMenuSelected

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem inventario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_creacioncupones;
    private javax.swing.JMenuItem jMenuItem_inventacupones;
    private javax.swing.JMenu jMenu_consultausuario;
    private javax.swing.JMenu jMenu_cv;
    private javax.swing.JMenu jMenu_salir;
    private javax.swing.JMenuItem nuevos_libros;
    // End of variables declaration//GEN-END:variables
}
