/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectob;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author emely
 */
public class Ventas extends javax.swing.JFrame {

    public Ventas() {
        initComponents();
        //eliminara los items que tenga el jcombox
        jComboBox_libros.removeAllItems();
        //agregar los usuarios que yo quiero
        jComboBox_libros.addItem("El principito");
        jComboBox_libros.addItem("El buque");

    }
    //metodo para pintar la tabla y las columnas y filas que lleva

    private void pintarTabla() {
        DefaultTableModel t = new DefaultTableModel(new String[]{"Titulo", "Cantidad", "Precio"}, ProyectoB.libros2.size());
        jTable1.setModel(t);

        TableModel tabla = jTable1.getModel();

        for (int i = 0; i < ProyectoB.libros2.size(); i++) {
            libros2 l = ProyectoB.libros2.get(i);
            tabla.setValueAt(l.titulo_venta, i, 0);
            tabla.setValueAt(l.cantidad_venta, i, 1);
            tabla.setValueAt(l.precio_venta, i, 2);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_cantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_precio = new javax.swing.JTextField();
        jButton_agregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_direccion = new javax.swing.JTextField();
        jTextField_cliente = new javax.swing.JTextField();
        jTextField_nit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField_total = new javax.swing.JTextField();
        jButton_registrarventa = new javax.swing.JButton();
        jTextField_vendedor = new javax.swing.JTextField();
        jButton_vendedor = new javax.swing.JButton();
        jButton_registrar = new javax.swing.JButton();
        jButton_calcular = new javax.swing.JButton();
        jComboBox_libros = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField_sIVA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_fecha = new javax.swing.JTextField();
        jButton_fecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Registo de ventas");

        jLabel2.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel2.setText("Vendedor");

        jLabel3.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel3.setText("Producto:");

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel5.setText("Precio:");

        jButton_agregar.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_agregar.setText("Agregar");
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel6.setText("Cliente");

        jLabel7.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel7.setText("Nit:");

        jLabel8.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel8.setText("Dirreción:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel9.setText("Total:");

        jButton_registrarventa.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_registrarventa.setText("Registrar venta");
        jButton_registrarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarventaActionPerformed(evt);
            }
        });

        jTextField_vendedor.setText("vendedor");

        jButton_vendedor.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_vendedor.setText("Seleccionar vendedor");

        jButton_registrar.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_registrar.setText("Registrar");
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });

        jButton_calcular.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_calcular.setText("Calcular");
        jButton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularActionPerformed(evt);
            }
        });

        jComboBox_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel10.setText("Total sin IVA:");

        jLabel11.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jLabel11.setText("Fecha:");

        jTextField_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fechaActionPerformed(evt);
            }
        });

        jButton_fecha.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        jButton_fecha.setText("Fecha");
        jButton_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 74, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBox_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton_agregar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_registrarventa)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton_calcular)
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jTextField_sIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(43, 43, 43)
                                                    .addComponent(jLabel9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_vendedor)
                                        .addGap(90, 90, 90)
                                        .addComponent(jTextField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_fecha)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(31, 31, 31)
                                        .addComponent(jTextField_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextField_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_direccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_registrar)
                                .addGap(12, 12, 12))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_vendedor)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_registrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_agregar)
                    .addComponent(jComboBox_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_registrarventa)
                    .addComponent(jButton_calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_sIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        // TODO add your handling code here:
        Clientes c = new Clientes();
        c.nombre_cliente = jTextField_cliente.getText();
        c.nit = jTextField_nit.getText();
        c.direccion = jTextField_direccion.getText();

        JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente");

        ProyectoB.clientes.add(c);
    }//GEN-LAST:event_jButton_registrarActionPerformed

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
        libros2 l = new libros2();

        l.titulo_venta = jComboBox_libros.getSelectedItem().toString();
        l.cantidad_venta = Integer.parseInt(jTextField_cantidad.getText());

        double precio = 0.0;

        String tituloSeleccionado = l.titulo_venta;

        switch (tituloSeleccionado) {
            case "El principito":
                precio = 10.00;
                break;
            case "El buque":
                precio = 5.00;
                break;
            default:
                JOptionPane.showMessageDialog(this, "Error: libro no encontrado");
                return; // Salir si hay un error
        }

        double subtotal = precio * l.cantidad_venta;

        l.precio_venta = subtotal;
        jTextField_precio.setText(String.valueOf(precio));

        ProyectoB.libros2.add(l);
        pintarTabla();
    }//GEN-LAST:event_jButton_agregarActionPerformed

    private void jButton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularActionPerformed

        double total = 0.0; // Inicializar el total

        // Recorrer la lista de libros2
        for (libros2 libro : ProyectoB.libros2) {
            total += libro.precio_venta; // Sumar al total

        }

        //el redondedo a dos decimales lo realice multiplicando el 100 y dividiendo el 100 si quiero que sea a 3 o mas se incrementaria 0 como por ejemplo 3 seria 1000.
        double TotalsIva = Math.round((total / 1.12) * 100.0) / 100.0;
        // Mostrar el total en jTextField7
        jTextField_total.setText(String.valueOf(total));
        jTextField_sIVA.setText(String.valueOf(TotalsIva));
    }//GEN-LAST:event_jButton_calcularActionPerformed

    private void jButton_registrarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarventaActionPerformed
        ventas c = new ventas();
        c.vendedor = jTextField_vendedor.getText();
        c.cliente_nombre = jTextField_cliente.getText();
        c.cliente_nit = jTextField_nit.getText();
        c.cliente_dirreción = jTextField_direccion.getText();
        c.cliente_total = Double.parseDouble(jTextField_total.getText());
        c.fecha = jTextField_fecha.getText();
        c.cliente_sIva = Double.parseDouble(jTextField_sIVA.getText());

        JOptionPane.showMessageDialog(this, "Venta agregada exitosamente");

        ProyectoB.ventas.add(c);

    }//GEN-LAST:event_jButton_registrarventaActionPerformed

    private void jTextField_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fechaActionPerformed


    }//GEN-LAST:event_jTextField_fechaActionPerformed

    private void jButton_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fechaActionPerformed
        // TODO add your handling code here:
        Calendar calendario = Calendar.getInstance();

        //obtener año, mes,dia
        int año = calendario.get(Calendar.YEAR);
        int mes = calendario.get(Calendar.MONTH);
        int dia = calendario.get(Calendar.DAY_OF_MONTH);

        jTextField_fecha.setText(String.valueOf(+año + "-" + mes + "-" + dia));
    }//GEN-LAST:event_jButton_fechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JButton jButton_calcular;
    private javax.swing.JButton jButton_fecha;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JButton jButton_registrarventa;
    private javax.swing.JButton jButton_vendedor;
    private javax.swing.JComboBox<String> jComboBox_libros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_cantidad;
    private javax.swing.JTextField jTextField_cliente;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_fecha;
    private javax.swing.JTextField jTextField_nit;
    private javax.swing.JTextField jTextField_precio;
    private javax.swing.JTextField jTextField_sIVA;
    private javax.swing.JTextField jTextField_total;
    private javax.swing.JTextField jTextField_vendedor;
    // End of variables declaration//GEN-END:variables
}
